version: '3'

services:

  zookeeper:
    image: zookeeper:3.4.9
    expose:
    - "2181"

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    extra_hosts:
      - "moby:127.0.0.1"

  master:
    image: singularities/spark
    command: start-spark master
    hostname: master
    ports:
      - "7070:7070"
  worker:
    image: singularities/spark
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    links:
      - master
  hbase:
   image: kevinsvds/hbase
   hostname: hbase
   ports:
     - "9090:9090"
     - "9095:9095"
     - "60000:60000"
     - "60010:60010"
     - "60020:60020"
     - "60030:60030"
  # links:
  #   - kafka
  #   - zookeeper
